#!/bin/bash -e

was=0;
counter=1;
if [ "$ZOOKEEPER_NODES" ] ; then
    IFS=',' read -ra NODES <<< "$ZOOKEEPER_NODES"
    for i in "${NODES[@]}"; do
        if [ "$i" = "`hostname -i`" ] ; then
            was=1;
        fi

        echo "server.$counter=$i:2888:3888" >> /opt/zookeeper-3.4.6/conf/zoo.cfg; 

        let counter=$counter+1;
    done

    if [ $was -eq 0 ] ; then
        echo "server.$counter=`hostname -i`:2888:3888" >> /opt/zookeeper-3.4.6/conf/zoo.cfg; 
        echo $counter > /var/lib/zookeeper/myid;
    fi
fi

/opt/zookeeper-3.4.6/bin/zkServer.sh start-foreground
